name: item_selector
version: 0.1.0
description: >-
  A generic item selector that works with ListView, GridView, Row, Column,
  or basically any parent widget that can have indexed child widgets.
homepage: https://github.com/jpnurmi/item_selector
repository: https://github.com/jpnurmi/item_selector
issue_tracker: https://github.com/jpnurmi/item_selector/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  interval_tree: ^0.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
